name: eventure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  go_router: ^16.2.4
  csv: ^6.0.0
  firebase_storage: ^13.0.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/